version: 0.3

scenario:
  resarea: [redz, corridors]
  sectors: [E] # ,E+EV,E+BEV,E+BEV+V2G] # [ E+EV, E+BEV, E+BEV+V2G ]
  cost: [csir-today, csir-moderate, csir-aggressive] #, IRP2016-Apr2016]
  opts: [LC, Ep, Co2L, BAU, LC-SAFE, Co2L-SAFE] #, LC-FL, LC-T, Ep-T, Co2L-T]

data:
  resarea:
    redz: data/REDZ_DEA_Unpublished_Draft_2015
    corridors: data/Power_corridors
 
year: "2040"
historical_year: "2012"

electricity:
  demand: 428.e+6     # 344TWh 2030, 428TWh 2040, 522TWh 2050
                      # IRP_Update_Assumptions_1904.pdf
  co2limit: 10.e+6    # 470.9e+5  # 0.1 * 470.9e+6 (2014 Electricity Sector)

  csp: false

  extendable_carriers:
    Generator: [OCGT, CCGT, Coal, Nuclear]
    StorageUnit: [Battery] # [CAES]

  buses:
    OCGT: [WEST COAST, EMPANGENI, PORT ELIZABETH] # Saldana Bay, Richards Bay, Coega
    CCGT: [WEST COAST, EMPANGENI, PORT ELIZABETH]
    Coal: [WATERBERG]
    Nuclear: [PORT ELIZABETH, PENINSULA] # Thyspunt, Koeberg

  BAU_mincapacities:
    Nuclear: 10000
    Coal: 10000

  SAFE_reservemargin: 0.1

  max_hours:
    Battery: 3
    CAES: 10

respotentials:
  # Gives us ball-park the available areas the IWES study reports
  landusetype_percent:
    wind:
      - [[7, 8, 9, 41], 80]
      # - [[5, 6], 50]
      # - [[11, 12, 14, 15], 10]
    solar:
      - [[7, 8, 9, 41], 80]
      # - [[11, 12, 14, 15], 50]
      # - [[46, 47, 51, 56, 64, 68, 72], 10]

  capacity_per_sqm:
    wind: 5   # half of 10 (IWES)
    solar: 16.5 # half of 33 (IWES)

hydro_inflow:
  countries: [ZA, MZ]
  cutout: za-mz-2012

lines:
  v_nom: 380.
  type: 'Al/St 240/40 4-bundle 380.0'

  # costs
  s_nom_factor: 0.7
  length_factor: 1.25

costs:
  # costs come from data/internal/IRP2016_Inputs_Technology-Costs (PUBLISHED).xlsx
  #sheetname: "IRP2016-Apr2016" # "CSIR-Apr2016"
  discountrate: 0.08

  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   Wind: Bla
  marginal_cost: # 
    PV: 0.01
    Wind: 0.015
  EUR_to_ZAR: 15.63

  emission_prices: # only used with the option Ep (emission prices)
    # Externality costs from Integrated Energy Plan by the ZA DOE
    co2: 0.27e+3
    sox: 7.6e+3
    nox: 4.5e+3
    hg: 41484.e-6 # is also part of the excel sheet
    particulate: 11.3e+3

transport:
  # 2014 Energy 702EJ
  # Table 18 in 20170331CSIR_EC_DOE p. 48 (64)
  energy_total: 25.2e+6 # 24 2030, 25.2 2040, 26.7 2050
  # efficiency_gain: 3.5 # Explanation
  availability_max: 0.95
  availability_mean: 0.8
  total_cars: 8.4e+6 # 8.0 2030, 8.4 2040, 8.9 2050
  car_battery_p_nom: 0.011 # 11kW 3-phase charger
  car_battery_e_nom: 0.05  # 50kWh battery
  # http://www.zeit.de/mobilitaet/2014-10/auto-fahrzeug-bestand
  standing_loss: 8.33e-5 # Buddischak
  efficiency: 0.9 # "

  # cars_per_person: 0.6

solving:
  tmpdir: /tmp
  options:
    clip_p_max_pu: 1.e-2
    load_shedding: true
    noisy_costs: true
    min_iterations: 4
    max_iterations: 10
    formulation: kirchhoff
    # max_iterations: 1
    # nhours: 10
  solver:
    name: gurobi_persistent
    threads: 4
    method: 2
    crossover: 0 # -1 (Choose freely)
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
    LogToConsole: 0
    OutputFlag: 1

plotting:
  map:
    figsize: [7, 7]
    boundaries: [16, -35, 33, -22]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3 # 1.e+3  #3.e+3

  costs_max: 800

  vre_techs: ["Wind", "PV"]
  conv_techs: ["OCGT", "CCGT", "Nuclear", "Coal"]
  storage_techs: ["Hydro", "CAES", "Battery", "Pumped storage", "Hydro+PS"]
  store_techs: ["Li ion", "water tanks"]
  load_carriers: ["AC load", "heat load", "Li ion load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"] 
  heat_links: ["heat pump", "resistive heater", "CHP heat", "CHP electric",
               "gas boiler", "central heat pump", "central resistive heater", "central CHP heat",
               "central CHP electric", "central gas boiler"]
  heat_generators: ["gas boiler", "central gas boiler", "solar thermal collector", "central solar thermal collector"]
  tech_colors:
    Wind: "xkcd:azure"
    Hydro: "g"
    ror: "g"
    Hydro+PS: "g"
    PV: "y"
    OCGT: "brown"
    OCGT marginal: "sandybrown"
    OCGT-heat: "orange"
    central gas boiler: "orange"
    gas boiler: "orange"
    gas boilers: "orange"
    gas boiler marginal: "orange"
    gas: "brown"
    lines: "k"
    AC line: "k"
    AC-AC: "k"
    transmission lines: "k"
    H2: "m"
    hydrogen storage: "m"
    Battery: "slategray"
    battery storage: "slategray"
    CAES: "lightgray"
    Nuclear: "r"
    Nuclear marginal: "r"
    Coal: "k"
    Coal marginal: "k"
    Lignite: "grey"
    Lignite marginal: "grey"
    CCGT: "orange"
    CCGT marginal: "orange"
    Diesel: "darkred"
    Diesel marginal: "darkred"
    heat pumps: "green"
    heat pump: "green"
    central heat pump: "green"
    resistive heater: "pink"
    central resistive heater: "pink"
    Sabatier: "turquoise"
    water tanks: "w"
    CHP: "r"
    CHP heat: "r"
    CHP electric: "r"
    central CHP heat: "r"
    central CHP electric: "r"
    Pumped storage: "g"
    Ambient: "k"
    AC load: "b"
    Heat load: "r"
    Li ion load: "grey"
    heat: "r"
    Li ion: "grey"
    district heating: "#CC4E5C"
  nice_names:
    # OCGT: "Gas"
    # OCGT marginal: "Gas (marginal)"
    #Battery: "Battery storage"
    lines: "Transmission lines"
    AC line: "AC lines"
    AC-AC: "DC lines"
    ror: "Run of river"
  nice_names_n:
    offwind: "offshore\nwind"
    onwind: "onshore\nwind"
    # OCGT: "Gas"
    H2: "Hydrogen\nstorage"
    # OCGT marginal: "Gas (marginal)"
    lines: "transmission\nlines"
    ror: "run of river"
